config/routes.rb
Rails.application.routes.draw do
  resources :friends, only: [:index, :create, :destroy]
  resources :user_stocks, only: [:create, :destroy]

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  
  root 'welcome#index'

  get "my_portfolio", to: "users#my_portfolio"
  get "my_friends", to: "users#my_friends"
  get "stocks_portfolio", to: "stocks#search_stocks_from_portfolio"
  post "stock_search", to: "stocks#search_stock"
  get "search_friends", to: "friends#search_friends"
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  def index
    @q = current_user.friends.ransack(params[:q])
    @friends = @q.result(distinct: true)
    @user = User.new
  end

  def create
  end

  def destroy
  end

  def search_friends
    @q = User.ransack(params[:q])
    @friends = @q.result(distinct: true)

    @friends = @friends.reject { |friend| friend[:id] == current_user.id }

    if @friends.empty?
      flash.now[:alert] = "No friend was found with the provided name"
    end

    friend_name = params[:q][:name_cont]
    if friend_name.blank?
      if params[:controller] == "friends"
        flash.now[:alert] = "Please, fill the name field to search a user!"
        @friends = []
      end
    end

    
    respond_to do |format|
      format.js {render partial: "friends/search_friends_js"}
    end
  end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/_friends_display.html.erb
<%if params[:controller] == "friends" %>
  <%= render "layouts/flash_messages" %>
<%end%>

<% if !@friends.empty? %>
  <div class="card card-header friends-result-display mb-4">
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Email</th>
          <th scope="col">Signed up Since</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @friends.each do |friend| %>
          <tr>
            <th scope="row"><%=friend.name%></th>
            <td><%=friend.email%></td>
            <td><%=friend.created_at%></td>
            <%if already_follow?(friend) %>
              <th scope="col">
                <span class="badge text-bg-secondary">You already follow this user </span>
              </th> 
            <%else%>
              <th scope="col">
                <%= link_to "#", class: "btn btn-success btn-sm" do%>
                  Follow
                <%end%>
              </th>
            <%end%>
          </tr>
        <%end%>
      </tbody>
    </table>
  </div>
<%end%>

app/views/friends/_friends_table.html.erb
<div class="card">
  <div class="card-body">
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Signed Up Since</th>
          <th>Actions</th>
        </tr>
      </thead>

      <tbody>
        <% friends.each do |friend| %>
          <tr>
            <td><%= friend.name %></td>
            <td><%= friend.email %></td>
            <td><%= following_since(current_user, friend).to_s(:long) %></td>
            <td>
              <%= link_to "#", class: "btn btn-warning btn-sm", method: :delete do%>
                <i class="fa-solid fa-user-minus me-2"></i> Stop Following
              <%end%>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/friends/_search_form_friends.html.erb
<div class="card my-5">

  <div class="card-header">
    <h4>Search a user by the name!</h4>
  </div>

  <%= search_form_for q, url: search_friends_path, remote: true, class: "mb-1" do |f| %>
    <div class="card-body">

      <div class="form-group row align-items-center">
        
        <div class="col-sm-5">
          <%= f.label :name, class: "form-label" %>
          <%= f.search_field :name_cont, class: "form-control form-control-lg" %>
        </div>
        
      </div>

    </div>

    <div class="card-footer">
      <div class="form-group row">
        <div class="col-sm-4  d-flex align-items-center">
          <%= button_tag(type: 'submit', class: 'btn btn-success') do %>
            <i class="fa-solid fa-magnifying-glass"></i> Search User
          <% end %>

          <%= link_to friends_path, class: "btn btn-secondary mx-3" do%>
            <i class="fa fa-broom"></i> Clear Fields
          <%end%>

          <%= link_to root_path, class: "btn btn-info" do%>
            <i class="fa-solid fa-arrow-left"></i> Back
          <%end%>
          
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/friends/_search_friends_js.js.erb
document.querySelector("#friends-display").innerHTML = '<%= escape_javascript(render "friends/friends_display", friends: @friends)%>'

app/views/friends/index.html.erb
<%= render "search_form_friends", q: @q%>

<div id="friends-display"></div>

<%if @friends %>
  <%= render "friends/friends_table", friends: @friends%>
<%end%>