config/routes.rb
Rails.application.routes.draw do
  resources :friends, only: [:index, :create, :destroy]
  resources :user_stocks, only: [:create, :destroy]

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  
  root 'welcome#index'

  get "my_portfolio", to: "users#my_portfolio"
  get "my_friends", to: "users#my_friends"
  get "stocks_portfolio", to: "stocks#search_stocks_from_portfolio"
  post "stock_search", to: "stocks#search_stock"
  get "search_friends", to: "friends#search_friends"
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord

  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "encrypted_password", "id", "name", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  def after_sign_in_path_for(resource)
    root_path
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:my_portfolio]
  
  def my_portfolio
    @q = current_user.stocks.ransack(params[:q])
    @stocks = @q.result(distinct: true)

    @stock = Stock.new
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_friends_display.html.erb
<%if params[:controller] == "users" %>
  <%= render "layouts/flash_messages" %>
<%end%>

<% if !@friends.empty? %>
  <div class="card card-header friends-result-display mb-4">
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Email</th>
          <th scope="col">Signed up Since</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @friends.each do |friend| %>
          <tr>
            <th scope="row"><%=friend.name%></th>
            <td><%=friend.email%></td>
            <td><%=friend.created_at%></td>
            <th scope="col">
              <%= link_to "#", class: "btn btn-success btn-sm" do%>
                Follow
              <%end%>
            </th>
          </tr>
        <%end%>
      </tbody>
    </table>
  </div>
<%end%>

app/views/users/_portfolio_stocks_result.js.erb
document.querySelector("#stocks_from_portfolio_results").innerHTML = '<%= escape_javascript(render "users/result_table", tracked_stocks: @stocks, q: @q) %>';

app/views/users/_result_table.html.erb
<%if params[:controller] == "stocks" %>
  <%= render "layouts/flash_messages" %>
<%end%>

<%if !tracked_stocks.empty? %>
  <div class="card">
    <div class="card-body">
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th><%= sort_link(q, :name, "Name") %></th>
            <th><%= sort_link(q, :ticker, "Ticker Symbol") %></th>
            <th><%= sort_link(q, :last_price, "Last Price") %></th>
            <th><%= sort_link(q, :created_at, "Created at") %></th>
            <th>Actions</th>
          </tr>
        </thead>

        <tbody>
          <% tracked_stocks.each do |stock| %>
            <tr>
              <td><%= stock.name %></td>
              <td><%= stock.ticker %></td>
              <td>$<%= stock.last_price %></td>
              <td><%= stock.created_at.to_s(:long) %></td>
              <td><%= link_to "Remove from Portfolio", user_stock_path(stock), class: "btn btn-danger", method: :delete%></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<%else%>
  <div class="alert alert-warning m-2" role="alert">
    It was not found any stocks!
  </div>
<%end%>   

app/views/users/_search_form.html.erb
<div class="card my-5">

  <div class="card-header">
    <h4>Search your portfolio</h4>
  </div>

  <%= search_form_for q, url: stocks_path, remote: true, class: "mb-1" do |f| %>
    <div class="card-body">

      <div class="form-group row align-items-center">
        
        <div class="col-sm-3">
          <%= f.label :ticker, class: "form-label" %>
          <%= f.search_field :ticker_cont, class: "form-control form-control-lg" %>
        </div>

        <div class="col-sm-5">
          <%= f.label :name, class: "form-label" %>
          <%= f.search_field :name_cont, class: "form-control form-control-lg" %>
        </div>
        
      </div>

    </div>

    <div class="card-footer">
      <div class="form-group row">
        <div class="col-sm-4  d-flex align-items-center">
          <%= button_tag(type: 'submit', class: 'btn btn-success') do %>
            <i class="fa-solid fa-magnifying-glass"></i> Search Stocks
          <% end %>

          <%= link_to my_portfolio_path, class: "btn btn-secondary mx-3" do%>
            <i class="fa fa-broom"></i> Clear Fields
          <%end%>

          <%= link_to root_path, class: "btn btn-info" do%>
            <i class="fa-solid fa-arrow-left"></i> Back
          <%end%>
          
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/_search_form_friends.html.erb
<div class="card my-5">

  <div class="card-header">
    <h4>Search a user by the name!</h4>
  </div>

  <%= search_form_for q, url: search_friends_path, remote: true, class: "mb-1" do |f| %>
    <div class="card-body">

      <div class="form-group row align-items-center">
        
        <div class="col-sm-5">
          <%= f.label :name, class: "form-label" %>
          <%= f.search_field :name_cont, class: "form-control form-control-lg" %>
        </div>
        
      </div>

    </div>

    <div class="card-footer">
      <div class="form-group row">
        <div class="col-sm-4  d-flex align-items-center">
          <%= button_tag(type: 'submit', class: 'btn btn-success') do %>
            <i class="fa-solid fa-magnifying-glass"></i> Search User
          <% end %>

          <%= link_to my_friends_path, class: "btn btn-secondary mx-3" do%>
            <i class="fa fa-broom"></i> Clear Fields
          <%end%>

          <%= link_to root_path, class: "btn btn-info" do%>
            <i class="fa-solid fa-arrow-left"></i> Back
          <%end%>
          
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/_search_form_individual.html.erb
<div class="card my-5">

  <div class="card-header">
    <h4>Use the Ticker Symbol to Search a Stock Here</h4>
  </div>

  <%= form_for @stock, url: stock_search_path, remote: true, class: "mb-1" do |f| %>
    <div class="card-body">

      <div class="form-group row align-items-center">
        
        <div class="col-sm-8 pe-0">
          <%= f.search_field :ticker, class: "form-control form-control-lg" %>
        </div>

        <div class="col-sm-2 px-0">
          <%= button_tag(type: 'submit', class: 'btn btn-success btn-lg') do %>
            <i class="fa-solid fa-magnifying-glass"></i>
          <% end %>
        </div>

      </div>

    </div>

    
  <% end %>
</div>

app/views/users/_search_form_portfolio.html.erb
<div class="card my-5">

  <div class="card-header">
    <h4>Search your portfolio</h4>
  </div>

  <%= search_form_for q, url: stocks_portfolio_path, remote: true, class: "mb-1" do |f| %>
    <div class="card-body">

      <div class="form-group row align-items-center">
        
        <div class="col-sm-3">
          <%= f.label :ticker, class: "form-label" %>
          <%= f.search_field :ticker_cont, class: "form-control form-control-lg" %>
        </div>

        <div class="col-sm-5">
          <%= f.label :name, class: "form-label" %>
          <%= f.search_field :name_cont, class: "form-control form-control-lg" %>
        </div>
        
      </div>

    </div>

    <div class="card-footer">
      <div class="form-group row">
        <div class="col-sm-4  d-flex align-items-center">
          <%= button_tag(type: 'submit', class: 'btn btn-success') do %>
            <i class="fa-solid fa-magnifying-glass"></i> Search Stocks
          <% end %>

          <%= link_to my_portfolio_path, class: "btn btn-secondary mx-3" do%>
            <i class="fa fa-broom"></i> Clear Fields
          <%end%>

          <%= link_to root_path, class: "btn btn-info" do%>
            <i class="fa-solid fa-arrow-left"></i> Back
          <%end%>
          
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/_stock_result.js.erb
document.querySelector("#result_stock").innerHTML = '<%= escape_javascript(render "users/stock_result_display", stock: @stock) %>';

app/views/users/_stock_result_display.html.erb
<%if params[:controller] == "stocks" %>
  <%= render "layouts/flash_messages" %>
<%end%>

<%if @stock.present?%>

  <div class="card" style="width: 18rem;">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        <strong>Ticker:</strong> <%=@stock.ticker%>
      </li>
      <li class="list-group-item">
        <strong>Name:</strong> <%=@stock.name%>
      </li>
      <li class="list-group-item">
        <strong>Last price:</strong> <%=@stock.last_price%>
      </li>
    </ul>
    <div class="card-footer">
      <%if user_has_stock(@stock) %>
        This stock is already added in your Portfolio
      <%elsif !user_can_track %>
        You have more than 10 stocks in your Portfolio!
      <%else%>
        <%= link_to user_stocks_path(ticker: @stock.ticker), method: :post, class: "btn btn-success btn-sm" do%>
          <i class="fa-solid fa-plus"></i> Add to Portfolio
        <%end%>
      <%end%>
    </div>
  </div>
<%end%>

app/views/users/my_friends.html.erb
<%= render "search_form_friends", q: @q%>

<div id="friends-display"></div>

<%if @friends %>
  <%= render "users/friends_table", friends: @friends%>
<%end%>

app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>

<%= render "users/search_form_individual"%>

<div id="result_stock"></div>

<%= render "users/search_form_portfolio", q: @q%>

<div id="stocks_from_portfolio_results">
  <%= render "users/result_table", q: @q, tracked_stocks: @stocks%>
</div>